Enhance session modal
pau-riosa/todo pull request #2
Opened 2023-01-23 19:39 UTC by Francisco-Castro

It takes a long time but finally I'm kind of happy with the result.

This PR handles the following parts:

- Dynamically creates a list of slots depending on the selected day. If today only create a list from the current time until the end of the day, otherwise it creates a full list of date from 12:00am - 11:40pm.
- Dynamically select a day depending on the selected day. If today select the next available slot, otherwise 8:00 am is the default selection.
- New button to display the calendar. It was a replacement for the click-away feature
- Reduce the data over the websocket when calendar is involved.
- Adds the `Todo.Tempo` module to handle some useful functions.
- Other minors details.

2023-01-24 12:00 UTC, pau-riosa requested changes
Great job overall, I do have questions and comments regarding this work. On the other hand, I would recommend to add documentation to every new functions and modules we are introducing for future reference. Thank you.

2023-01-24 12:00 UTC, pau-riosa commented on lib/todo/tempo.ex
> +defmodule Todo.Tempo do
It would be best if we can add moduledoc here for future preference. 
We also need to put some docs on how we can use these functions.

2023-01-24 12:00 UTC, pau-riosa commented on lib/todo_web/live/components/input/calendar_month_input.ex
> +  def preload([%{timezone: timezone}] = list_of_assigns) do
What if there is no timezone in the assigns, how we can handle it?

2023-01-24 12:00 UTC, pau-riosa commented on lib/todo_web/live/components/input/time_input.ex
> +    make_interval_times(~D[2014-09-22], [days: 1], step)
Is the hardcoded date intended?

2023-01-24 12:00 UTC, pau-riosa commented on lib/todo_web/live/components/input/time_input.ex
> +      |> Timex.set(second: 0, microsecond: {000_000, 6})
How does this one worked?

2023-01-24 14:31 UTC, Francisco-Castro commented on lib/todo/tempo.ex
> +defmodule Todo.Tempo do
It makes sense! Adding docs is something that I rarely do. I'll add some info about this module. Thanks @pau-riosa !

2023-01-24 14:37 UTC, Francisco-Castro commented on lib/todo_web/live/components/input/calendar_month_input.ex
> +  def preload([%{timezone: timezone}] = list_of_assigns) do
That's is a great question! Do you know if the client cannot send us a timezone? In "normal" conditions we are going to have timezone, right?

2023-01-24 14:38 UTC, Francisco-Castro commented on lib/todo_web/live/components/input/time_input.ex
> +    make_interval_times(~D[2014-09-22], [days: 1], step)
Right! It doesn't matter what day we take because all of them has 24 hours.

2023-01-24 14:43 UTC, Francisco-Castro commented on lib/todo_web/live/components/input/time_input.ex
> +      |> Timex.set(second: 0, microsecond: {000_000, 6})
This part rounds the time. For example if I clicked on create session and the datetime is something like "01/01/2023 08:11:12.123456" then this part is going to return "01/01/2023 08:20:00.000000" Seconds and microseconds are setup to zeros. The shift is going to move the minutes to the next slot of time. It makes sense?

2023-01-28 02:04 UTC, pau-riosa approved these changes

2023-01-28 02:04 UTC, merged